#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: CI - CPP, Python Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - branch-*

env:
  MAVEN_OPTS: -Xmx1024m -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3

jobs:
  changed_files_job:
    name: 'Changed files check'
    runs-on: ubuntu-20.04
    outputs:
      changes_outcome: ${{ steps.changes.outcome }}
      has_source_files: ${{ steps.changes.outputs.src }}
    steps:
      - id: changes
        uses: dorny/paths-filter@v2
        # ignore failures until https://github.com/dorny/paths-filter/issues/73 is fixed
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            src:
              # pattern syntax uses https://github.com/micromatch/picomatch
              - '!((site2|deployment)/**)'

  cpp-tests:
    needs: changed_files_job
    if: needs.changed_files_job.outputs.changes_outcome=='failure' || needs.changed_files_job.outputs.has_source_files == 'true'
    name:
    runs-on: ubuntu-20.04
    timeout-minutes: 120

    steps:
      - name: Checkout pull request HEAD commit
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout pushed commit on branch
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v2

      - name: Tune Runner VM
        uses: ./.github/actions/tune-runner-vm

      - name: Clean Disk
        uses: ./.github/actions/clean-disk

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository/*/*/*
            !~/.m2/repository/org/apache/pulsar
          key: ${{ runner.os }}-cpp-m2repository-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Replace maven's wagon-http version
        run: sudo ./build/ci_build_functions.sh ci_replace_maven_wagon_http_library

      - name: build package
        run: mvn -B -ntp -q install -Pcore-modules -DskipTests

      - name: build cpp artifacts
        run: |
          echo "Build C++ client library"
          export CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug -DBUILD_DYNAMIC_LIB=OFF -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so"
          pulsar-client-cpp/docker-build.sh

      - name: run c++ tests
        run: pulsar-client-cpp/docker-tests.sh
